pipeline{
    agent any
    stages{
        stage("build")
        {
           withMaven {
                              sh "mvn -v"
                            }
            steps{


                echo "build step"
            }
        }
    }
}