pipeline{
    agent any
      tools {
            maven 'Maven 3.8.4'
            jdk 'jdk8'
        }
    stages{
        stage("build")
        {
            steps{
                sh '''
                                    echo "PATH = ${PATH}"
                                    echo "M2_HOME = ${M2_HOME}"
                                '''
                echo "build step"
            }
        }
    }
}